### ISSUE TITLE
Continous changes

### ISSUE THREAD

**Issue by thigg** [IBM/cloudant-java-sdk#149]
**Is your feature request related to a problem? Please describe.**
We need to query changes continously. This does not seem possible with the new sdk

**Describe the solution you'd like**
A continous change listener that i can query for next and hasNext iterator-style.
The resulting Item should allow me to get the Document from the change.

**Comment by mojito317** [comment]
Hi @thigg!

Right now all I can suggest is a workaround. 

If you need to query the changes continuously, you can set the feed to [continuous mode](https://docs.couchdb.org/en/stable/api/database/changes.html?highlight=_changes#changes-continuous) with a hearbeat, which is not so ideal, but working:
> setting up new HTTP connections just to tell the client that nothing happened puts unnecessary strain on CouchDB

Call `postChangesAsStream` and read the response lines with the reader's iterator. With this, you can read the non-empty lines of the response and you can get the document from the change setting the `includeDocs=true`, but you have to deserialize the string to a JSON first and then get the `doc` attribute from your JSON if you would like to turn it into a `Document` object.

Something like this:
```java
PostChangesOptions changesOptions = new PostChangesOptions.Builder()
    .db("dbName")
    .feed(PostChangesOptions.Feed.CONTINUOUS)
    .heartbeat(60000)
    .includeDocs(true)
    .build();

try (InputStream is = client.postChangesAsStream(changesOptions).execute().getResult()) {
    BufferedReader in = new BufferedReader(new InputStreamReader(is));

    while (in.lines().iterator().hasNext()) {
        String line = in.readLine();
        if (line!= null && !line.isEmpty()){
            // deserialize the line into a JSON Object
            // make a Document object from the `doc` param of your JSON Object
        }
    }
} catch (IOException e) {
    ...
}
```
