### ISSUE TITLE
Document::isDeleted may return null

### ISSUE THREAD

**Issue by thigg** [IBM/cloudant-java-sdk#152]
**Describe the bug**
The isDeleted property might lead to unexpected NullpointerExceptions.

Eg. with a simple `if(myDoc.isDeleted())` you can see NPEs. 

**Solution**
The method should either return an Optional or a boolean.

 - SDK Version 0.0.25

**Comment by mojito317** [comment]
Hi @thigg!

`isDeleted` represents the `_deleted` flag in a document which is only available if the document was removed so a `null` check would be enough for you.

**Comment by thigg** [comment]
Hi,
thanks, this is nice to know!

But isn't it very likely that many people just assume they can use the `if(doc.isDeleted())` construct and get an unexpected exception?

**Comment by mojito317** [comment]
Yeah, it makes sense, but it is also hard to implement since our SDK is generated from an OpenAPI spec, and setting a default value is not and will not be supported in the generator. This is a correct implementation if we strictly align with the API documentation, a non-deleted document does not contain this field, so it will be `null`. Javadoc for this method says also:

> Deletion flag. _Available if document was removed_.

**Comment by thigg** [comment]
I understand your argument, and that its complicated. But I would expect that this causes problems in every single project that uses this SDK.

I think a good choice would be, to return an `Optional<Boolean>` instead of a `Boolean`. This should be easy to implement in you generator on nullable fields. This would not break your OpenAPI spec, as its equivalent to returning a boolean which could be null.
It is good style anyway to make nulls more explicit.

Is there any place where I can/should escalate this issue to?

**Comment by ricellis** [comment]
We've reported this against the generator and are looking into potential mitigations that might make this more user-friendly.
