### ISSUE TITLE
Support for 429 retry?

### ISSUE THREAD

**Issue by al-tr** [IBM/cloudant-java-sdk#153]
Is there some embedded 429 retry/replay solution like it is in the old library?
https://github.com/cloudant/java-cloudant/blob/master/cloudant-http/src/main/java/com/cloudant/http/interceptors/Replay429Interceptor.java

**Comment by mojito317** [comment]
Hi @al-tr!

This SDK partly supports [automatic retries](https://github.com/IBM/ibm-cloud-sdk-common/blob/main/README.md#automatic-retries):
> This Java SDK supports a limited retry feature that will retry `429 - Too Many Requests` errors with exponential backoff if no `Retry-After` response header is present.

But currently, the retry solution can work only if you set the configuration of your Cloudant instance programmatically, where you need to use programmatic authentication as well. Please check how you can set it [in our API Docs](https://cloud.ibm.com/apidocs/cloudant?code=python#programmatic-authentication).

After your authenticator is ready you can pair it with a HTTP configuration similar to my example below, where `defaultInterval=1` and `maxRetries=3` :
```java
import com.ibm.cloud.sdk.core.http.HttpConfigOptions;
```

```java
HttpConfigOptions.Builder builder = new HttpConfigOptions.Builder();
builder.enableRateLimitRetry(authenticator, 1, 3);
client.configureClient(builder.build());
```

**Comment by al-tr** [comment]
@mojito317 thank you :)
