### ISSUE TITLE
support _revs_limit

### ISSUE THREAD

**Issue by thigg** [IBM/cloudant-java-sdk#159]
**Is your feature request related to a problem? Please describe.**
Support the `_revs_limit` endpoint or provide a way to reuse the authentication and send arbitrary requests to the server.

**Describe the solution you'd like**
Have a method to get the value of `_revs_limit`, similar to `postRevsDiff`

**Describe alternatives you've considered**
reuse the authentication and send arbitrary requests to the server.

**Comment by emlaver** [comment]
Hello @thigg, the `_revs_limit` endpoint is not configurable in Cloudant so we don't expose this endpoint in the SDKs.

**Comment by ricellis** [comment]
Just noting here the workaround documented in https://github.com/IBM/cloudant-java-sdk/issues/161#issuecomment-902805404
