### ISSUE TITLE
support manual compaction with _compact

### ISSUE THREAD

**Issue by thigg** [IBM/cloudant-java-sdk#161]
**Is your feature request related to a problem? Please describe.**
Support the `/{db}/_compact` endpoint or provide a way to reuse the authentication and send arbitrary requests to the server.

**Describe the solution you'd like**
Have a method to get the value of `_compact`, similar to `postRevsDiff`

**Describe alternatives you've considered**
reuse the authentication and send arbitrary requests to the server.

**Comment by emlaver** [comment]
Hi @thigg, this endpoint is automatically handled and not available in Cloudant.
e.g.
```
curl https://<cloudant_account>.../db/_compact
{"error":"forbidden","reason":"compaction is automatic on Cloudant"}
```
For more details about the server compatibility with this SDK, please see https://github.com/IBM/cloudant-java-sdk#features

**Comment by thigg** [comment]
what about the alternative? creating a way to reuse the authentication and run custom requests?

**Comment by emlaver** [comment]
There's an option to create an OkHttp request and pass it to the SDK client object.  You can add existing authentication to the custom request using `client.getAuthenticator().authenticate()`: 
```
        Cloudant client = Cloudant.newInstance("SERVER");
        String dbName = "your-db";
        HttpUrl requestUrl =  HttpUrl.parse(client.getServiceUrl()).newBuilder().addPathSegment(dbName).addPathSegment("_compact").build();
        Request.Builder rb = new Request.Builder().url(requestUrl).get();
        client.getAuthenticator().authenticate(rb);
        Response response = client.getClient().newCall(rb.build()).execute();
        System.out.println(response.body().string());
```
If you're using session cookie auth, you'll need to disable gzip compression with `client.enableGzipCompression(false);`.  This is mentioned in https://github.com/IBM/cloudant-java-sdk/blob/master/KNOWN_ISSUES.md#session-authentication
