### ISSUE TITLE
Ilegal Document_id

### ISSUE THREAD

**Issue by kimlizette** [IBM/cloudant-java-sdk#174]
I'm working on Java and when I try to create a Cloudant Document, it shows me the following error 
![image](https://user-images.githubusercontent.com/23389957/133854361-0c0bfbf3-b395-48eb-86cc-4098cf5b7aec.png)

I tried the example:
![image](https://user-images.githubusercontent.com/23389957/133854645-352eb18e-2797-4e51-84da-a2611b3da9dd.png)

And it still does not work. Can you please advise?

**Comment by ricellis** [comment]
Are you using a [partitioned database](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-database-partitioning)?
I think the only reason the server would return `illegal_docid` would be if you are trying to write a document to a partitioned database, but not using the partitioned doc ID format of `partition:id`.

You can [get the reason](https://cloud.ibm.com/apidocs/cloudant?code=java#code-example-java) the server rejected the document ID from the error by handling the exception e.g.
```java
try {
  DocumentResult response = service.putDocument(documentOptions).execute().getResult();
} catch (BadRequestException e) {
  // get "reason" from error
  System.out.println(e.getDebuggingInfo().get("reason"));
}
```

I expect the reason will be `Doc id must be of form partition:id` - so either use a non-partitioned database or change your doc ID to use a suitable partition key.

**Comment by kimlizette** [comment]
It was partitioned, thank you!
