### ISSUE TITLE
Current release includes vulnerable version of Gson

### ISSUE THREAD

**Issue by youming-lin** [IBM/cloudant-java-sdk#192]
**Describe the bug**
Gson version 2.8.8 and under has a known vulnerability:
https://snyk.io/vuln/SNYK-JAVA-COMGOOGLECODEGSON-1730327

This has been fixed in 2.8.9. Please update Gson version to 2.8.9 or later and release a new version of this SDK.

Edit:
I see that this is being addressed in https://github.com/IBM/cloudant-java-sdk/pull/190

**Comment by eiri** [comment]
@youming-lin yes, we raised an issue with core's team and will update our sdk as soon as they'll release a new version with a fix for gson >= 2.8.9 compatibility.

**Comment by vmatyusGitHub** [comment]
The latest [0.0.30](https://github.com/IBM/cloudant-java-sdk/releases/tag/v0.0.30) version contains the needed vulnerability fix.
