### ISSUE TITLE
Cloudant::postIndex(...).execute() Is broken

### ISSUE THREAD

**Issue by snackerphi** [IBM/cloudant-java-sdk#194]
**Describe the bug**

`cloudant.postIndex(...).execute()` should return success (200 - OK), but instead throws a BadRequestException (400 - "Bad Request") due to:
```
{
    "error": "invalid_sort_field",
    "reason": "Invalid sort field: {[{<<\"name\">>,<<\"my_field\">>}]}"
}
```
The json that it sends to the server is:
```json
{
    "index": {
        "fields": [
            {
                "name": "my_field"
            }
        ]
    },
    "name": "my_db_index"
}
```
But it should be this instead (according to [the couchdb docs](https://docs.couchdb.org/en/stable/api/database/find.html#db-index)):
```json
{
    "index": {
        "fields": [
            "my_field"
        ]
    },
    "name": "my_db_index"
}
```

[Cloudant::postIndex(...) at 2867](https://github.com/IBM/cloudant-java-sdk/blob/36e91707347aab54be4b7291d9a10f71ddae4894/modules/cloudant/src/main/java/com/ibm/cloud/cloudant/v1/Cloudant.java#L2867) appears to be where the issue is.
```java
contentJson.add("index", com.ibm.cloud.sdk.core.util.GsonSingleton.getGson().toJsonTree(postIndexOptions.index()));
```
This is adding the json object with `"name"` = `"my_db_index"` instead of just adding the list of field names as an array.

**To Reproduce**

The following java code will reproduce the issue:
```java
    List<IndexField> fields = new ArrayList();
    fields.add( new IndexField.Builder().name( "my_field" ).build() );
    Response<IndexResult> irlt = cloudant.postIndex(
                                    new PostIndexOptions.Builder()
                                        .db( "my_db" )
                                        .name( "my_db_index" )
                                        .index(
                                            new IndexDefinition.Builder()
                                                    .fields( fields )
                                                    .build()
                                        ).build()
                                ).execute();
```

**Expected behavior**

It should create the index and return successfully (200 - OK or similar)

**Screenshots**

**Must gather (please complete the following information):**
 - SDK Version : `0.0.29`
 - Java Version : `openjdk version "1.8.0_302"`
 - Name of service : `couchdb`
 - Name of operation that you're trying to invoke : `POST /my_db/_index`

**Additional context**

One workaround is to violate the generic contract of the api via:
```java
    List fields = new ArrayList();
    fields.add( "my_field" );
    Response<IndexResult> irlt = cloudant.postIndex(
                                    new PostIndexOptions.Builder()
                                        .db( "my_db" )
                                        .name( "my_db_index" )
                                        .index(
                                            new IndexDefinition.Builder()
                                                    .fields( fields ) /* actually a List<String> instead of List<IndexField> */
                                                    .build()
                                        ).build()
                                ).execute();
```
```

**Comment by snackerphi** [comment]
Actually, this is not a problem.  You have to use `IndexField.Builder::add( <name>, <asc|desc|...> )` as below:

```java
    List<IndexField> fields = new ArrayList();
    fields.add( new IndexField.Builder().add( "my_field", "asc" ).build() );
    Response<IndexResult> irlt = cloudant.postIndex(
                                    new PostIndexOptions.Builder()
                                        .db( "my_db" )
                                        .name( "my_db_index" )
                                        .index(
                                            new IndexDefinition.Builder()
                                                    .fields( fields )
                                                    .build()
                                        ).build()
                                ).execute();
```

**Comment by ricellis** [comment]
>You have to use IndexField.Builder::add( <name>, <asc|desc|...> ) as below

Right, the `IndexField` object can take 2 different forms depending on the index type:
1. For type `json` indexes: a named field, sort direction mapping e.g.
    * `{"foo", "asc"}`
    * `new IndexField.Builder().add("foo","asc").build()`
2. For type `text` indexes a `name`/`type` object e.g.
    * `{"name": "bar", "type": "string"}`
    * `new IndexField.Builder().name("bar").type(IndexField.Type.STRING).build()`

The [example in the docs](https://cloud.ibm.com/apidocs/cloudant?code=java#postindex) is for 1, but we'll try and make the difference more clear in the documentation.
