### ISSUE TITLE
Programmatic IAM authentication not working while ENV variables do

### ISSUE THREAD

**Issue by elias-mueller** [IBM/cloudant-java-sdk#275]
Version used: 0.1.1

Hello,

I'm not sure if I'm doing something wrong but the behavior is confusing. When I set CLOUDANT_URL and CLOUDANT_APIKEY env variables my `Cloudant.newInstance()` works fine. But when I create the instance with the following code I get a 401 authorization error:

```
var authenticator = new IamAuthenticator.Builder().url("***").apikey("***).build();
var service = new Cloudant(Cloudant.DEFAULT_SERVICE_NAME, authenticator);
```

**Comment by eiri** [comment]
Are you trying to use env auth and programmatic auth simultaneously?

Are you sure you are using correct api key? The reason I'm asking is that I see you are changing IAM url in your programmatic example, but not mentioning doing so in env auth case.
