### ISSUE TITLE
getDocumentXxx() fails to find documents whose id contains '+'

### ISSUE THREAD

**Issue by jnhagelberg** [IBM/cloudant-java-sdk#339]
The issue here is that the character `+` in document ids is not being encoded to `%2B` in the URL sent to cloudant.  As a result, cloudant throws a 404 not found exception for the document.

To reproduce:

1) Create a document with any content with the id 
```
c___likes_fvt_@@{hello}@@~!@#$%^&*()_+{}|:"<>?,./;'[]\-=`_c___sort_of_likes_fvt_@@{hello}@@~!@#$%^&*()_+{}|:"<>?,./;'[]\-=`
```
2) Attempt to fetch the document back using Cloudant.getDocumentAsStream(...) or Cloudant.getDocument(...).

The call fails with 404 not found

We saw the issue with getDocumentAsStream()  and getDocument().  We suspect it affects all getDocumentXxx variants.

**Comment by jnhagelberg** [comment]
Closing - it looks like this is a known issue

**Comment by GMishx** [comment]
Was any solution found for the `+` in ID is found?

**Comment by GMishx** [comment]
Found it: https://github.com/IBM/cloudant-java-sdk/blob/51b7da64dea925dc1dd0b2a980dba93e0c899297/KNOWN_ISSUES.md#path-elements-containing-the--character
