### ISSUE TITLE
Keep <7.7.0 testng version when running Java 8 tests

### ISSUE THREAD

**Issue by mojito317** [IBM/cloudant-java-sdk#369]
As https://github.com/IBM/cloudant-java-sdk/pull/368#issuecomment-1369663317 says, `testng` is no longer supporting Java 8. If we want to keep updating this test dependency but also support Java 8 and run Java 8 in our test matrix we can temporarily ([till Nov 2026](https://www.ibm.com/support/pages/semeru-runtimes-support), or till the core team finds another solution) separate the dependency versions used based on the Java version.

For this, I think the easiest way would be to update our pom file with a custom build profile for the builds with <JDK11 versions. With this, we can override the latest (dependabot pulled version) with testng `7.6.x` which is the latest version that supports Java 8. I would note here, testng was not working since `7.4.x` due to another issue mentioned here: https://github.com/IBM/cloudant-java-sdk/pull/216, so we may have a testng version lower than `7.6.x` for Java 8.

```xml
<project>
  <properties>
     <testng-version>7.7.1</testng-version>
     ..
  </properties>
  ..

  <build>
    <profiles>
      <profile>
        <id>testng-version-less-than-jdk11</id>
        <activation>
          <jdk>(,11)</jdk>
        </activation>
        <properties>
          <testng-version>7.6.1</testng-version>
          ..
        </properties>
      </profile>
    <profiles>
  </build>
</project>
```

**Comment by mojito317** [comment]
I also unsubscribed from `testng` dependabot bumps until this issue is resolved: https://github.com/IBM/cloudant-java-sdk/pull/368#issuecomment-1372142925

**Comment by mojito317** [comment]
This is going to be addressed in https://github.com/IBM/cloudant-java-sdk/pull/382, which introduce Mockito instead of testng, a nicer and better solution.

**Comment by ricellis** [comment]
Not really - mockito is replacing powermock, which allows us to move up to testng >= 7.4, but I think we'll still need to make a profile or disable the Java 8 action branch if we want to move to >=7.7

**Comment by ricellis** [comment]
Whatever we do here we should extend to also cover the mockito 4.x vs 5.x case, see e.g. https://github.com/IBM/cloudant-java-sdk/pull/385

**Comment by mojito317** [comment]
> mockito is replacing powermock

yeah, right I mixed `testng` with `powermock`, my bad 😆

**Comment by ricellis** [comment]
This impacts our unit and integration tests, but not the regression tests we run on the built jars where we can continue to get Java 8 coverage. I think we should use this ticket to remove Java 8 for the maven driven UTs/ITs thus allowing us to upgrade the test dependencies.

**Comment by emlaver** [comment]
@ricellis do we want to run build/compile steps against Java 8? If we don't want to remove Java 8 from GHA then here's a profile that works to run everything except tests for Java 8: 
```xml
        <profile>
            <id>run-tests-on-jdk11+</id>
            <activation>
                <jdk>(,11)</jdk>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>default-test</id>
                                <phase>none</phase>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>default-testCompile</id>
                                <phase>none</phase>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

```

**Comment by ricellis** [comment]
We should remove Java 8 from GHA.
I'm not sure we need the profile. If the profile is there is it obvious that tests have been skipped?
I'd almost rather the tests failed (or failed to run) if someone attempts to run them on Java 8 than being silently skipped and thus giving a false sense of success.
