### ISSUE TITLE
DesignDocumentViewIndex is missing fields

### ISSUE THREAD

**Issue by jnhagelberg** [IBM/cloudant-java-sdk#417]
The following fields are missing from the `DesignDocumentViewIndex` class:

`purge_seq`
`update_seq`

I don't see them in the latest code in `main`, and we are using 0.4.0.

These fields (especially `update_seq`) are important because they tell us how up to date the view is.

Here is an example:
```
{
  "name": "asset_names_view_v1",
  "view_index": {
    "updates_pending": {
      "minimum": 0,
      "preferred": 0,
      "total": 0
    },
    "waiting_commit": false,
    "waiting_clients": 0,
    "updater_running": false,
    "update_seq": 32062,
    "sizes": {
      "file": 11053696,
      "external": 1048032,
      "active": 1421907
    },
    "signature": "3fcd53713e9674a6e87c635f6912fd56",
    "purge_seq": 0,
    "language": "javascript",
    "compact_running": false,
    "collator_versions": [
      "153.104"
    ]
  }
}
```

**Comment by ricellis** [comment]
Thanks for reporting this - we intentionally excluded the `update_seq` and `purge_seq` from the SDK(s), I'm reviewing the reasoning behind that to see if we could revise that decision.

FWIW I do not believe that `update_seq` is a reliable way of tracking whether a view is up-to-date; where we do [document this `update_seq` (for the HTTP native endpoint)](https://cloud.ibm.com/apidocs/cloudant#getdesigndocumentinformation) we explicitly say:
>Do not rely on this property for counting the number of updates.

As such I suspect that `updates_pending` may be a more reliable way to check how up to date the view is, but I know that is also missing from the model at present so I'll be looking into whether we are able to get that added.

**Comment by ricellis** [comment]
I've confirmed that `updates_pending` is the recommended way to see if a view is up-to-date (we are adding it to the model via #420).

If your obejctive is to avoid delays for index building when querying then this tip (thanks @rnewson) will likely help:
>wait for `preferred` to hit `0`. that means at least one copy of every range is up to date (and hence can be queried without further delay)

**Comment by ricellis** [comment]
The updates pending information is now available from `DesignDocumentViewIndex` in the new [0.5.1 release](https://github.com/IBM/cloudant-java-sdk/releases/tag/v0.5.1).

**Comment by jnhagelberg** [comment]
Thanks!!
