### ISSUE TITLE
Cloudant.deleteIndex( ... ).execute() does not create the correct HTTP request using IndexInformation.getDdoc().

### ISSUE THREAD

**Issue by snackerphi** [IBM/cloudant-java-sdk#462]
**Describe the bug**

To delete an index, the `Cloudant::deleteIndex(... .ddoc( ii.getDdoc() ) ...)` is sending:
`DELETE /my_foo-db/_index/_design/_design%2F8a49ddc19c9f8084e81ff8783637b1b30fea460f/json/my_foo-db_name_idx HTTP/1.1`
However, according to [CouchDB DELETE index](https://docs.couchdb.org/en/stable/api/database/find.html#delete--db-_index-designdoc-json-name), it should be:
`DELETE /my_foo-db/_index/8a49ddc19c9f8084e81ff8783637b1b30fea460f/json/my_foo-db_name_idx HTTP/1.1`

**To Reproduce**

1. We query the couchdb database for indexes using the Cloudant java API.
    `List<IndexesInformation> rii cloudant.getIndexesInformation(...)`
2. We loop through the `rii` to determine if there is an index that needs to be deleted.
3. We find `IndexInformation ii = rii.get( ... );` that needs to be deleted.
4. We attempt to delete it with:
`     Response<Ok> ro = cloudant.deleteIndex(
            new DeleteIndexOptions.Builder()
                    .db( dbName )
                    .index( idxName )
                    .ddoc( ii.getDdoc() )
                    .type( ii.getType() )
                    .build()
    ).execute();`
5. this fails with the error: `com.ibm.cloud.sdk.core.service.exception.NotFoundException: not_found`

Using curl:
- This works:  `curl -X DELETE 'http://localhost:5983/my_foo-db/_index/_design/8a49ddc19c9f8084e81ff8783637b1b30fea460f/json/my_foo-db_name_idx' -H 'Authorization: Basic YWJjOjEyMw==' -v`
- This does not:  `curl -X DELETE 'http://localhost:5983/my_foo-db/_index/_design/_design%2F8a49ddc19c9f8084e81ff8783637b1b30fea460f/json/my_foo-db_name_idx' -H 'Authorization: Basic YWJjOjEyMw==' -v`

**Expected behavior**

HTTP 200 OK

**Screenshots**

**Must gather (please complete the following information):**
 - SDK Version:  0.5.4
 - Java Version:  OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
 - Name of service that you're trying to use:  Cloudant -> CouchDB
 - Name of operation that you're trying to invoke:  DELETE index

**Additional context**

Changing `.ddoc( ii.getDdoc() )` to `.ddoc( ii.getDdoc().replaceFirst( "^_design/", "" ) )` will work.

Is this the way it is expected to work?

**Comment by emlaver** [comment]
Hello @snackerphi thanks for reporting this.  From our API docs, when getting the list of indexes the [response object has this description for `ddoc` field](https://cloud.ibm.com/apidocs/cloudant?code=java#getindexesinformation):
<img width="454" alt="Screenshot 2023-08-29 at 11 12 39 AM" src="https://github.com/IBM/cloudant-java-sdk/assets/10552966/15523d00-da51-4cd6-9387-7eeb1aa023a5">

When getting and [deleting an index](https://cloud.ibm.com/apidocs/cloudant?code=java#deletedesigndocument), the description for `ddoc` states that the string should not contain `_design` prefix:
<img width="707" alt="Screenshot 2023-08-29 at 11 14 24 AM" src="https://github.com/IBM/cloudant-java-sdk/assets/10552966/13f6db1d-0774-48e2-9925-e00a2d5741ee">

It's working as expected but we will update `getIndexesInformation` response description to make it clear that `ddoc` includes a `_design` prefix.

**Comment by snackerphi** [comment]
OK, thanks!
