### ISSUE TITLE
Cloudant linking problem in javadoc

### ISSUE THREAD

**Issue by vmatyusGitHub** [IBM/cloudant-java-sdk#65]
**Describe the bug**

In javadoc some `Cloudant` link reference is not parsed properly:

This link is not working because it want to link a class from another maven module.

There are 3 links like this in the javadoc:
* 1 in common/package-info.java 
* 2 in CouchDbSessionAuthenticator.java

A possible solution would be to use `<detecetLinks>`. But in this case the `mvn verify` in Travis throws the following error:
`error: reference not found
[ERROR]      *  {@link com.ibm.cloud.cloudant.v1.Cloudant} client automatically.`
See [Travis pipeline](https://travis-ci.com/github/IBM/cloudant-java-sdk/jobs/461112349)

As an alternate solution link can be defined as HTML links, like `<a href="../v1/Cloudant.html"><code>Cloudant</code></a>`

**Screenshots**
![Screen Shot 2021-01-08 at 11 40 31](https://user-images.githubusercontent.com/26717393/104006158-66707880-51a6-11eb-9c67-48252e04c23b.png)

**Additional context**
The common code could be used later by different models, so it is not guaranteed to be `v1`. Worth considering to also remove these links.

**Comment by ricellis** [comment]
We should just delete those doc links. They won't be accurate when we introduce additional model based modules that share `com.ibm.cloud.cloudant.common` anyway because there will be multiple client models that might be callers of the package and authenticator.
